version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api-car-rendal
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - pgadmin

  db:
    build: .docker/postgres/
    container_name: api-car-rendal-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-cars
